Add eslint setup instructions
thiagodelgado111/eslint-config-orbitdb pull request #5
Opened 2018-08-30 16:04 UTC by thiagodelgado111

I've added some info on how to setup `eslint` for other projects from scratch here pointing to their `getting-started`. Is that better @haadcode? :)

Closes #4

2018-08-30 16:58 UTC, RichardLitt commented on README.md
> +## Usage
This isn't Usage,  but an Install section, it looks like?

2018-08-30 16:58 UTC, RichardLitt commented on README.md
> +  Linux/OSX users can run
Add colon

2018-08-30 16:59 UTC, RichardLitt requested changes
Pretty good. I have a few comments, and some fixes to push later. (See https://github.com/orbitdb/repo-template for what those are, if you want to do them, here?)

2018-08-30 19:07 UTC, thiagodelgado111 commented
Fixed and added the missing files, should be good to go now :)

2018-08-31 08:07 UTC, haadcode commented
I tried setting it up again and while got closer, noticed a few ways we can improve the developer experience. 

I personally find it really nice to try out a repo when the installation and usage instructions are clear and explicit, so I wrote the step-by-step instructions to the README in #7 and PRed a change to the deps in #6 (required for #7 to work as written). 

In #7 I also removed the unrelated files (COC, contributing guidelines, npmignore) to clean up this PR ("Add eslint setup instructions"). We should create separate PRs for adding those.

If you like the modified version of the README in #7, feel free to merge it here and we can merge this to master.

2018-09-05 18:17 UTC, RichardLitt commented
@haadcode When you get a chance, take a look at @thiagodelgado111's comments in #6 and #7.

2018-12-11 17:14 UTC, RichardLitt commented
Going with standard for now. Closing this for the moment.

2018-12-11 17:14 UTC, closed without merging